### PR TITLE
Load domain from config

### PR DESCRIPTION
**Pull request by filipef101**
No idea how nobody complained about this before

First time contribution to an homebridge plugin, so not familiar with how UI for config is shown.
I didn't see the UI updated after installing my fork, showing the domain input, but maybe the frontend fetches the UI from npm? 
I does default to io.meross.com so nothing should be broken? - would be good to double check as not sure if existing users will get the default domain inserted in their config, or if default keys are only when adding plugins. 
Happy to also fallback to the the js side.

Feel free to change anything on the PR to merge it 👍

### CODE REVIEW

**Comment by filipef101** [comment]
@bwp91 The homeassistant addon for example does allow/make the user input an endpoint.
Without this I could not login as my endpoint is `iotx-eu.meross.com`

**Comment by filipef101** [comment]
Probably documentation updates should also be included

**Comment by bwp91** [comment]
out of interest what is your error message from the plugin when you try to use it?

**Comment by bwp91** [comment]
i made a couple of changes just to suit the plugin better, please let me know if you are still happy with the current state of the PR and i can merge it in

**Comment by filipef101** [comment]
Shouldn't the default option be present? Otherwise I think the docs really should mention that the domain needs to be filled and

**Comment by filipef101** [comment]
And will likely break the plugin for existing users @bwp91 no?

**Pull request merged**
