### PR TITLE
Adding in MSL-320

### PR DESCRIPTION
**Pull request by jhives82**
Added in MSL-320.  I dont do a lot of programming / javascript so feel free to alter the namespace change.

Closed first pr to clean up spaces / tabs.

### CODE REVIEW

**Comment by donavanbecker** [comment]
I will merge into the beta branch, which will push out a new beta to test.

**Comment by donavanbecker** [comment]
@jhives82 Wanna give it a try?

Beta: `3.5.1-beta.1`

**Comment by jhives82** [comment]
Installed the beta via the UI -- appears to be working just fine.  No errors in the log either.

**Comment by donavanbecker** [comment]
@jhives82 I will release a new update in a few days. Let it play out.

**Pull request merged**
